  version: '3.8'
  services:
    app:
      build: .
      image: my-spring-security
      ports:
        - "8080:8080"
      depends_on:
        db:
            condition: service_healthy
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/authentication
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: secret

    db:
      image: mysql:8
      restart: always
      environment:
        MYSQL_DATABASE: authentication
        MYSQL_ROOT_PASSWORD: secret
      ports:
        - "3306:3306"
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 5
